name: 'Grid.ai Run'
on:
   workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string
      run_time:
        required: true
        type: int
  # schedule:
    # Runs "at 10pm" (see https://crontab.guru)
    # Please remove the # to activate the cron
   #- cron: '*/30 * * * *'
 

jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}   
      - name: get-run-status
        run: |
          # run name is truncated within github action due to screen size.  make it short
          grid status
          export RUN_STATUS=$(grid status ${{ github.event.inputs.run_name }} |  awk '{print $2 "," $6}' | grep ${{ github.event.inputs.run_name }} | cut -d ',' -f 2 )
          echo "RUN_STATUS $RUN_STATUS"
          export RUN_HOURS=$(grid status ${{ github.event.inputs.run_name }} |  awk '{print $2 "," $10}' | grep ${{ github.event.inputs.run_name }} | cut -d ',' -f 2 | cut -d ':' -f 1 | cut -d '-' -f 2 )
          echo "RunHOURS1: $RUN_HOURS"
          if [ "$RUN_STATUS" != "running" ]
          then
             echo "Run is not running"
          elif [ "$RUN_HOURS" > "${{ github.event.inputs.run_time }}" ]
          then
            echo "Run duration has exceeded crossed threhold: {{ github.event.inputs.run_time }} Run is being Stopped"
            grid stop run ${{ github.event.inputs.run_name }}
          fi
        shell: bash
