name: 'Grid.ai Stop Run'
on:
   workflow_dispatch:
    inputs:
      run_name:
        required: true
        type: string
  # schedule:
    # Runs "at 10pm" (see https://crontab.guru)
    # Please remove the # to activate the cron
   #- cron: '*/30 * * * *'
 

jobs:
  gridai-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gridai-actions/gridai-login@v0
        with:
          gridai-username: ${{ secrets.GRIDAI_USERNAME }} 
          gridai-key: ${{ secrets.GRIDAI_KEY }}        
      - name: get-run-status
        run: |
          export COLUMNS=512
          # run name is truncated within github action due to screen size.  make it short
          export RUN_STATUS=$(grid status ${{  secrets.RUN_NAME }} |  awk '{print $2 "," $6}' | grep ${{ secrets.RUN_NAME }} | cut -d ',' -f 2 )
          echo "RUN_STATUS $RUN_STATUS"
          export RUN_HOURS=$(grid status ${{ secrets.RUN_NAME }} |  awk '{print $2 "," $10}' | grep ${{ secrets.RUN_NAME }} | cut -d ',' -f 2 | cut -d ':' -f 1 | cut -d '-' -f 2 )
          echo "RunHOURS1: $RUN_HOURS"
          if [ "$RUN_STATUS" != "running" ]
          then
             echo "Run is not running"
          elif [ "$RUN_HOURS" > "${{ secrets.RUN_DURATION }}" ]
          then
            echo "Run duration has exceeded crossed threhold: ${RUN_DURATION} Run is being Stopped"
            grid stop run ${{ secrets.RUN_NAME }}
          fi
        shell: bash
